---
# Playbook to configure the k8s master
- hosts: all
  become: true
  tasks:
  # Install dependency packages and add vagrant to docker user group
  - name: Install packages that allow apt to be used over HTTPS
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

  - name: Add an apt signing key for Docker
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Install docker and its dependecies
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    notify:
      - docker status

  - name: Add vagrant user to docker group
    ansible.builtin.user:
      name: vagrant
      group: docker

  # Kubelet will not start if the system has swap enabled, so disable swap
  - name: Remove swapfile from /etc/fstab
    ansible.posix.mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    ansible.builtin.command: swapoff -a
    when: ansible_swaptotal_mb > 0

  # Install k8s binaries
  - name: Add an apt signing key for k8s
    ansible.builtin.apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for k8s
    ansible.builtin.apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install k8s binaries
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet
        - kubeadm
        - kubectl

  - name: Configure node ip
    ansible.builtin.lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
      create: yes

  - name: Restart kubelet
    ansible.builtin.service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Copy docker.json to /etc/docker/daemon.json
    ansible.builtin.copy:
      src: docker.json
      dest: /etc/docker/daemon.json
      mode: 0600

  - name: Enable and restart docker
    ansible.builtin.systemd:
      name: docker
      state: restarted
      enabled: yes
      daemon_reload: yes

  # Initialise the k8s cluster
  - name: Initialize the k8s cluster using kubeadm
    ansible.builtin.command: kubeadm init --apiserver-advertise-address="0.0.0.0" --apiserver-cert-extra-sans="10.120.60.10" --node-name k8s-master --pod-network-cidr=10.120.0.0/16

  # Setup the kube config file for the root user to access the k8s cluster
  - name: Setup kubeconfig for root user
    ansible.builtin.command: "{{ item }}"
    with_items:
      - mkdir -p /root/.kube
      - cp -i /etc/kubernetes/admin.conf /root/.kube/config

  # Setup the kube config file for the vagrant user to access the k8s cluster
  - name: Setup kubeconfig for vagrant user
    ansible.builtin.command: "{{ item }}"
    with_items:
      - mkdir -p /home/vagrant/.kube
      - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
      - chown vagrant:vagrant /home/vagrant/.kube/config

  # Setup the container networking provider and the network policy engine
  - name: Install calico pod network
    become: false
    ansible.builtin.command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml

  # Generate kube join command for joining the node to the k8s cluster and store the command in the file named join-command
  - name: Generate join command
    ansible.builtin.command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to file
    ansible.builtin.template:
      content: "{{ join_command.stdout_lines[0] }}"
      dest: /tmp/join-command

  - name: Fetch file to local
    ansible.builtin.fetch:
      src: /tmp/join-command
      dest: /tmp/join-command

  # Setup a handler for checking Docker daemon
  handlers:
    - name: docker status
      ansible.builtin.service:
        name: docker
        state: started
