---
# Playbook to configure the k8s loadbalancer
- hosts: all
  become: true
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Install HAProxy
      ansible.builtin.apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Copy haproxy.cfg to /etc/haproxy/haproxy.cfg
      ansible.builtin.copy:
        src: files/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        mode: 0600
      notify: restart haproxy

  # Setup a handler for restarting haproxy
  handlers:
    - name: restart haproxy
      ansible.builtin.service:
        name: haproxy
        state: restarted
